# Generated by Django 6.0.6 on 2026-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KursAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('yosh', models.PositiveIntegerField()),
                ('yonalish', models.CharField(max_length=20)),
                ('tajriba_bor', models.BooleanField(default=False)),
                ('qoshimcha', models.TextField(blank=True)),
                ('yuborilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
